############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

hugoVersion:
  extended: true

imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-reveal
  - path: HugoBlox/hugo-blox-bootstrap/modules/blox-bootstrap
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind
  - path: hugomods/shortcodes


